# Netlify configuration for frontend-only deployment
[build]
  # Build command for the frontend
  command = "npm run build:frontend"
  # Output directory after build
  publish = "dist/public"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (will be set in Netlify dashboard)
[build.environment]
  NODE_ENV = "production"
  VITE_API_URL = "https://your-backend-api.com/api"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"